description: Create/update Cloudflare domains
inputs:
  delete:
    default: "false"
    description: Whether to delete the record name
    required: true
  proxy:
    default: "false"
    description: Whether to enable Cloudflare proxy for the record name
    required: false
  record:
    description: Record name to be created/updated
    required: true
  target:
    description: Target/IP address the record name should point to
    required: false
  ttl:
    default: "3600"
    description: Time-to-live for the record name
    required: false
  type:
    description: Type of the record name to be created/updated
    required: false
  zone-name:
    description: Zone name of the record name
    required: true
name: Yet Another Cloudflare Action
outputs: {}
runs:
  using: docker
  image: docker://ghcr.io/marcelofcandido/yet-another-cloudflare-action:latest
  env:
    INPUT_RECORD: ${{ inputs.record }}
    INPUT_ZONE_NAME: ${{ inputs.zone-name }}
    INPUT_DELETE: ${{ inputs.delete }}
    INPUT_TYPE: ${{ inputs.type }}
    INPUT_TARGET: ${{ inputs.target }}
    INPUT_PROXY: ${{ inputs.proxy }}
    INPUT_TTL: ${{ inputs.ttl }}
