env:
  IMAGE_NAME: ${{ github.repository }}
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          cache: true
          go-version-file: 'go.mod'

      - name: Run Go tests
        run: go test ./...

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}

      - id: string
        name: Convert repository to lowercase
        run: echo "repository_lowercase=$(echo ${{ env.IMAGE_NAME }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - id: meta
        name: Extract metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ steps.string.outputs.repository_lowercase }}
          tags: |
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha,prefix={{tag}}-
            latest
      - id: platforms
        name: Determine platforms
        run: |
          if [ -n "${{ github.event.inputs.platforms }}" ]; then
            echo "platforms=${{ github.event.inputs.platforms }}" >> $GITHUB_OUTPUT
          else
            echo "platforms=linux/amd64,linux/arm64" >> $GITHUB_OUTPUT
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          build-args: |
            BUILDKIT_INLINE_CACHE=1
          # Use both GitHub Actions and registry caching
          cache-from: |
            type=gha
            type=registry,ref=${{ env.REGISTRY }}/${{ steps.string.outputs.repository_lowercase }}:buildcache
          cache-to: |
            type=gha,mode=max
            type=registry,ref=${{ env.REGISTRY }}/${{ steps.string.outputs.repository_lowercase }}:buildcache,mode=max
          context: .
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ steps.platforms.outputs.platforms }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}

name: Build and Push Docker Image (Multi-Platform)

on:
  push:
    tags:
      - 'v*'
      - '*.*.*'
  workflow_dispatch:
    inputs:
      platforms:
        default: 'linux/amd64,linux/arm64'
        description: 'Platforms to build for'
        required: false
        type: string
