jobs:
  test-action:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: read
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          username: ${{ github.actor }}
      - env:
          CLOUDFLARE_API_EMAIL: ${{ secrets.CLOUDFLARE_API_EMAIL }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        id: create_record
        name: Create DNS Record
        uses: marcelofcandido/yet-another-cloudflare-action@master
        with:
          proxy: true
          record: ${{ secrets.TEST_RECORD_NAME }}
          target: www.bing.com
          ttl: 300
          type: CNAME
          zone-name: ${{ secrets.CLOUDFLARE_ZONE_NAME }}
      - env:
          CLOUDFLARE_API_EMAIL: ${{ secrets.CLOUDFLARE_API_EMAIL }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        id: update_record
        name: Update DNS Record
        uses: marcelofcandido/yet-another-cloudflare-action@master
        with:
          proxy: true
          record: ${{ secrets.TEST_RECORD_NAME }}
          target: www.google.com
          ttl: 300
          type: CNAME
          zone-name: ${{ secrets.CLOUDFLARE_ZONE_NAME }}
      - env:
          CLOUDFLARE_API_EMAIL: ${{ secrets.CLOUDFLARE_API_EMAIL }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        id: delete_record
        name: Delete DNS Record
        uses: marcelofcandido/yet-another-cloudflare-action@master
        with:
          delete: true
          record: ${{ secrets.TEST_RECORD_NAME }}
          zone-name: ${{ secrets.CLOUDFLARE_ZONE_NAME }}

name: Test Deployed Action

on:
  workflow_run:
    branches:
      - master
    types: [completed]
    workflows: ["Build and Push Docker Image"]
